/**
 * ChatStore — persists chats in localStorage, manages sliding window memory
 *
 * Memory strategy for small-ctx local models:
 *   - Always include the last WINDOW_SIZE message pairs (user+ai)
 *   - Older messages are replaced by a rolling summary string
 *   - Summary is generated by the model itself (async, on demand)
 *   - Summary is cached per chat — only regenerated when window slides past threshold
 *
 * Data shape per chat (localStorage key: cue-chats):
 * {
 *   id:       string,
 *   name:     string,
 *   created:  number,
 *   updated:  number,
 *   settings: { agent, tone, context },
 *   messages: [{ role, content, ts }],
 *   summary:  string | null,   -- compressed memory of messages beyond window
 *   summarizedUpTo: number     -- index of last message included in summary
 * }
 */

const STORE_KEY   = 'cue-chats';
const WINDOW_SIZE = 8;   // recent message pairs kept in full — safe for 2048 ctx
const SUMMARY_THRESHOLD = 12; // summarize when history exceeds this many messages

/** Strip attachments suffix and trim for sidebar title until smart title runs. */
function deriveFallbackTitle(rawContent) {
  let s = String(rawContent || '').replace(/\s+/g, ' ').trim();
  const cut = s.search(/\n\nAttachments\b/i);
  if (cut > 0) s = s.slice(0, cut).trim();
  if (!s) return 'Chat';
  if (s.length <= 44) return s;
  const words = s.split(/\s+/).slice(0, 8).join(' ');
  return words.length > 44 ? words.slice(0, 41) + '…' : words;
}

class ChatStore {
  constructor() {
    this._chats = this._load();
    this._activeId = localStorage.getItem('cue-active-chat') || null;

    // Ensure active chat exists
    if (this._activeId && !this._chats[this._activeId]) this._activeId = null;

    // Create default chat if none exist
    if (Object.keys(this._chats).length === 0) {
      this._activeId = this.createChat('New Chat');
    } else if (!this._activeId) {
      // Pick most recent
      this._activeId = Object.values(this._chats)
        .sort((a, b) => b.updated - a.updated)[0].id;
    }

    // Backfill new settings on older chats
    for (const chat of Object.values(this._chats)) {
      chat.settings = chat.settings || {};
      if (!chat.settings.agent) chat.settings.agent = 'auto';
      if (!chat.settings.tone) chat.settings.tone = 'interview';
      if (typeof chat.settings.context !== 'string') chat.settings.context = '';
      if (!chat.settings.brain) chat.settings.brain = 'balanced';
      if (typeof chat.settings.autoTitleDone !== 'boolean') chat.settings.autoTitleDone = false;
    }

    localStorage.setItem('cue-active-chat', this._activeId);
  }

  // ── CRUD ───────────────────────────────────────────────────

  createChat(name) {
    const id = 'chat_' + Date.now() + '_' + Math.random().toString(36).slice(2, 6);
    this._chats[id] = {
      id,
      name: name || 'New Chat',
      created: Date.now(),
      updated: Date.now(),
      settings: { agent: 'auto', tone: 'interview', context: '', brain: 'balanced', autoTitleDone: false },
      messages: [],
      summary: null,
      summarizedUpTo: -1
    };
    this._save();
    return id;
  }

  deleteChat(id) {
    delete this._chats[id];
    this._save();
    if (this._activeId === id) {
      const remaining = Object.values(this._chats).sort((a, b) => b.updated - a.updated);
      this._activeId = remaining.length ? remaining[0].id : this.createChat('New Chat');
      localStorage.setItem('cue-active-chat', this._activeId);
    }
    return this._activeId;
  }

  renameChat(id, newName) {
    if (!this._chats[id]) return;
    this._chats[id].name = newName.trim() || 'Chat';
    this._chats[id].settings = this._chats[id].settings || {};
    this._chats[id].settings.autoTitleDone = true;
    this._save();
  }

  duplicateChat(id) {
    const src = this._chats[id];
    if (!src) return null;
    const nid = 'chat_' + Date.now() + '_' + Math.random().toString(36).slice(2, 6);
    this._chats[nid] = {
      id: nid,
      name: (src.name || 'Chat') + ' — copy',
      created: Date.now(),
      updated: Date.now(),
      settings: { ...(src.settings || {}) },
      messages: JSON.parse(JSON.stringify(src.messages || [])),
      summary: src.summary,
      summarizedUpTo: src.summarizedUpTo
    };
    this._save();
    return nid;
  }

  clearMessages(id) {
    if (!this._chats[id]) return;
    this._chats[id].messages       = [];
    this._chats[id].summary        = null;
    this._chats[id].summarizedUpTo = -1;
    this._chats[id].updated        = Date.now();
    this._save();
  }

  setActive(id) {
    if (!this._chats[id]) return;
    this._activeId = id;
    localStorage.setItem('cue-active-chat', id);
  }

  saveSettings(id, settings) {
    if (!this._chats[id]) return;
    Object.assign(this._chats[id].settings, settings);
    this._save();
  }

  // ── Messages ──────────────────────────────────────────────

  addMessage(chatId, role, content) {
    const chat = this._chats[chatId];
    if (!chat) return;
    chat.messages.push({ role, content, ts: Date.now() });
    chat.updated = Date.now();

    // Provisional title from first user message (refined after first assistant reply)
    if (role === 'user' && chat.messages.filter(m => m.role === 'user').length === 1) {
      chat.name = deriveFallbackTitle(content);
    }

    this._save();
  }

  // ── Memory / Sliding Window ───────────────────────────────
  // Returns the message array to send to the model:
  //   [system, ...summaryMsg?, ...recentMessages]
  // Total token estimate stays well within 2048 ctx.

  buildContext(chatId, systemPrompt) {
    const chat = this._chats[chatId];
    if (!chat) return [{ role: 'system', content: systemPrompt }];

    const msgs    = chat.messages;
    const total   = msgs.length;

    // How many recent messages to include in full
    const windowStart = Math.max(0, total - WINDOW_SIZE * 2);
    const recent      = msgs.slice(windowStart);

    const out = [{ role: 'system', content: systemPrompt }];

    // If there are older messages beyond the window, inject summary
    if (windowStart > 0 && chat.summary) {
      out.push({
        role: 'user',
        content: '[Earlier conversation summary — treat as established context]:\n' + chat.summary
      });
      out.push({ role: 'assistant', content: 'Understood, I have context from our earlier discussion.' });
    }

    // Add recent messages
    recent.forEach(m => out.push({ role: m.role, content: m.content }));

    return out;
  }

  // Check if we should summarize (called after adding AI message)
  shouldSummarize(chatId) {
    const chat = this._chats[chatId];
    if (!chat) return false;
    const unsummarized = chat.messages.length - (chat.summarizedUpTo + 1);
    return unsummarized > SUMMARY_THRESHOLD;
  }

  // Called with the generated summary text
  applySummary(chatId, summaryText) {
    const chat = this._chats[chatId];
    if (!chat) return;
    // Keep the summary; mark how far we've summarized
    // (we summarize everything except the last WINDOW_SIZE pairs)
    const keepFrom = Math.max(0, chat.messages.length - WINDOW_SIZE * 2);
    chat.summary        = summaryText;
    chat.summarizedUpTo = keepFrom - 1;
    this._save();
  }

  // Build a summarization prompt from old messages
  buildSummaryMessages(chatId) {
    const chat = this._chats[chatId];
    if (!chat) return null;
    const total    = chat.messages.length;
    const keepFrom = Math.max(0, total - WINDOW_SIZE * 2);
    if (keepFrom === 0) return null;

    const toSummarize = chat.messages.slice(0, keepFrom);
    const formatted   = toSummarize
      .map(m => (m.role === 'user' ? 'User: ' : 'Assistant: ') + m.content.slice(0, 400))
      .join('\n\n');

    return [
      {
        role: 'system',
        content: 'You are a concise summarizer. Summarize the following conversation into 3-5 bullet points that capture the key topics, decisions, and context. Be specific — include tech names, problem statements, and conclusions. Output only the bullet points, no preamble.'
      },
      { role: 'user', content: formatted }
    ];
  }

  // ── Getters ───────────────────────────────────────────────

  getChat(id)     { return this._chats[id] || null; }
  getActive()     { return this._chats[this._activeId] || null; }
  getActiveId()   { return this._activeId; }
  getAllChats()    {
    return Object.values(this._chats).sort((a, b) => b.updated - a.updated);
  }

  getMemoryInfo(chatId) {
    const chat = this._chats[chatId];
    if (!chat) return null;
    const total  = chat.messages.length;
    const window = Math.min(total, WINDOW_SIZE * 2);
    return {
      total,
      inWindow: window,
      hasSummary: !!chat.summary,
      summaryLength: chat.summary ? chat.summary.length : 0
    };
  }

  // ── Persistence ───────────────────────────────────────────

  _load() {
    try {
      const raw = localStorage.getItem(STORE_KEY);
      return raw ? JSON.parse(raw) : {};
    } catch (_) { return {}; }
  }

  _save() {
    try {
      // Trim very long messages before saving to avoid localStorage limits
      const trimmed = {};
      for (const [id, chat] of Object.entries(this._chats)) {
        trimmed[id] = {
          ...chat,
          messages: chat.messages.map(m => ({
            ...m,
            content: m.content.slice(0, 8000)  // cap at 8k chars per message
          }))
        };
      }
      localStorage.setItem(STORE_KEY, JSON.stringify(trimmed));
    } catch (e) {
      console.warn('ChatStore save failed:', e.message);
    }
  }
}

window.chatStore = new ChatStore();
